const drones=[['DJI Mini 2','C0','< 250 g','Mini 2 classique, selon configuration et marquage de classe applicable.'],['DJI Mini 3','C0','< 250 g','Vérifier le marquage C0 et la configuration exacte du drone.'],['DJI Mini 4 Pro','C0','< 250 g','Vérifier le marquage C0 sur l’appareil et la documentation.'],['DJI Mini 5 Pro','C0*','selon version','Vérifier impérativement la classe inscrite sur le drone.'],['DJI Neo','C0','< 250 g','Vérifier le marquage C0 de la version utilisée.'],['DJI Neo 2','C0*','selon version','Vérifier impérativement la classe inscrite sur le drone.'],['DJI Flip','C0','< 250 g','Vérifier le marquage C0 et la configuration exacte.']];
const select=document.querySelector('#droneSelect'),info=document.querySelector('#droneInfo');
drones.forEach((d,i)=>{const o=document.createElement('option');o.value=i;o.textContent=d[0];select.appendChild(o)});
function renderDrone(){const d=drones[select.value];info.innerHTML=`<div class="info"><strong>${d[1]} · ${d[2]}</strong><span>${d[3]}</span></div>`}select.addEventListener('change',renderDrone);renderDrone();
const rules=[...document.querySelectorAll('.rules input')],decision=document.querySelector('#decision');
function updateDecision(){const n=rules.filter(x=>x.checked).length;if(n===rules.length){decision.textContent='✅ Contrôles cochés — effectue encore la vérification officielle de la zone avant décollage.';decision.style.background='#eaf7ef';decision.style.color='#17663a'}else{decision.textContent=`⚠️ Vérification incomplète — ${n}/${rules.length} contrôles validés.`;decision.style.background='#fff4d6';decision.style.color='#7a4d00'}}rules.forEach(x=>x.addEventListener('change',updateDecision));
document.querySelector('#resetBtn').onclick=()=>{document.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);updateDecision()};
let map,marker;
const restrictionBox=document.querySelector('#restrictionStatus');
function formatDistance(m){return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`}
function updateExternalMaps(lat,lon){document.querySelector('#airOpsBtn').href=`https://airops-supuav.fr/map/#5.05/${lat.toFixed(5)}/${lon.toFixed(5)}`;document.querySelector('#geoBtn').href=`https://www.geoportail.gouv.fr/donnees/restrictions-uas-categorie-ouverte-et-aeromodelisme`}
async function checkRestrictions(lat,lon){restrictionBox.classList.remove('hidden');restrictionBox.className='restrictionStatus loading';restrictionBox.innerHTML='🔎 Analyse des restrictions géographiques autour de la position…';try{const r=await fetch(`https://api.cquest.org/drone?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}&rayon=5000`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();const features=Array.isArray(data.features)?data.features:[];const inside=features.filter(f=>Number(f?.properties?.distance_m)===0);const nearby=features.filter(f=>Number(f?.properties?.distance_m)>0).slice(0,5);if(inside.length){const rows=inside.slice(0,6).map(f=>{const p=f.properties||{};const h=p.limite_alti_m!=null?` · hauteur max ${p.limite_alti_m} m`:'';return `<li><b>Restriction détectée sur la position</b>${h}</li>`}).join('');restrictionBox.className='restrictionStatus danger';restrictionBox.innerHTML=`<strong>⛔ Restriction géographique détectée</strong><p>La position se trouve dans au moins une zone connue par la base interrogée.</p><ul>${rows}</ul><small>Vérification obligatoire sur Géoportail et SIA/NOTAM avant tout vol.</small>`}else if(nearby.length){const rows=nearby.map(f=>{const p=f.properties||{};const d=Number(p.distance_m)||0;const h=p.limite_alti_m!=null?` · plafond ${p.limite_alti_m} m`:'';return `<li>${formatDistance(d)}${h}</li>`}).join('');restrictionBox.className='restrictionStatus warning';restrictionBox.innerHTML=`<strong>⚠️ Restrictions à proximité</strong><p>Aucune zone de la base n'est indiquée comme intersectant exactement le point, mais des zones existent dans un rayon de 5 km.</p><ul>${rows}</ul><small>La base ne couvre pas toutes les restrictions temporaires.</small>`}else{restrictionBox.className='restrictionStatus safe';restrictionBox.innerHTML='<strong>ℹ️ Aucune restriction détectée dans la base interrogée</strong><p>Aucune zone connue n’a été trouvée dans un rayon de 5 km autour de la position.</p><small>Cela ne signifie pas que le vol est autorisé : vérifie aussi Géoportail, SIA/NOTAM, AirOps et les restrictions locales.</small>'}}catch(e){restrictionBox.className='restrictionStatus warning';restrictionBox.innerHTML=`<strong>⚠️ Contrôle automatique indisponible</strong><p>Impossible d'interroger la base de restrictions depuis l'application.</p><small>Utilise les boutons Géoportail officiel et AirOps ci-dessus pour effectuer la vérification.</small>`}}
document.querySelector('#locateBtn').onclick=()=>{const s=document.querySelector('#locationStatus');if(!navigator.geolocation){s.textContent='Géolocalisation non disponible sur cet appareil.';return}s.textContent='Recherche de ta position…';navigator.geolocation.getCurrentPosition(p=>{const lat=p.coords.latitude,lon=p.coords.longitude;s.textContent=`Position : ${lat.toFixed(5)}, ${lon.toFixed(5)}.`;updateExternalMaps(lat,lon);checkRestrictions(lat,lon);document.querySelector('#map').classList.remove('hidden');if(!map){map=L.map('map').setView([lat,lon],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}else map.setView([lat,lon],14);if(marker)marker.remove();marker=L.marker([lat,lon]).addTo(map).bindPopup('Ta position').openPopup()},e=>{s.textContent='Position indisponible. Autorise la localisation puis réessaie.';restrictionBox.className='restrictionStatus warning';restrictionBox.classList.remove('hidden');restrictionBox.innerHTML='⚠️ Autorise la géolocalisation pour lancer le contrôle automatique.'},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})};
document.querySelector('#mapBtn')?.addEventListener('click',()=>window.open('https://www.geoportail.gouv.fr/donnees/restrictions-uas-categorie-ouverte-et-aeromodelisme','_blank','noopener'));