const drones=[['DJI Mini 2','C0','< 250 g','Mini 2 classique, selon configuration et marquage de classe applicable.'],['DJI Mini 3','C0','< 250 g','Vérifier le marquage C0 et la configuration exacte du drone.'],['DJI Mini 4 Pro','C0','< 250 g','Vérifier le marquage C0 et la documentation.'],['DJI Mini 5 Pro','C0*','selon version','Vérifier impérativement la classe inscrite sur le drone.'],['DJI Neo','C0','< 250 g','Vérifier le marquage C0 de la version utilisée.'],['DJI Neo 2','C0*','selon version','Vérifier impérativement la classe inscrite sur le drone.'],['DJI Flip','C0','< 250 g','Vérifier le marquage C0 et la configuration exacte.']];
const select=document.querySelector('#droneSelect'),info=document.querySelector('#droneInfo');
drones.forEach((d,i)=>{const o=document.createElement('option');o.value=i;o.textContent=d[0];select.appendChild(o)});
function renderDrone(){const d=drones[select.value];info.innerHTML=`<div class="info"><strong>${d[1]} · ${d[2]}</strong><span>${d[3]}</span></div>`}select.addEventListener('change',renderDrone);renderDrone();
const rules=[...document.querySelectorAll('.rules input')],decision=document.querySelector('#decision');
function updateDecision(){const n=rules.filter(x=>x.checked).length;if(n===rules.length){decision.textContent='✅ Contrôles cochés — effectue encore la vérification officielle de la zone avant décollage.';decision.style.background='#eaf7ef';decision.style.color='#17663a'}else{decision.textContent=`⚠️ Vérification incomplète — ${n}/${rules.length} contrôles validés.`;decision.style.background='#fff4d6';decision.style.color='#7a4d00'}}rules.forEach(x=>x.addEventListener('change',updateDecision));
document.querySelector('#resetBtn').onclick=()=>{document.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);updateDecision()};
let map,marker;
const restrictionBox=document.querySelector('#restrictionStatus');
function updateExternalMaps(lat,lon){const airOpsUrl=`https://airops-supuav.fr/map/#5.05/${lat.toFixed(5)}/${lon.toFixed(5)}`;document.querySelector('#airOpsBtn').href=airOpsUrl;document.querySelector('#geoBtn').href='https://www.geoportail.gouv.fr/donnees/restrictions-uas-categorie-ouverte-et-aeromodelisme';return airOpsUrl}
function checkRestrictions(lat,lon){const airOpsUrl=updateExternalMaps(lat,lon);const frame=document.querySelector('#airOpsFrame');if(frame){frame.src=airOpsUrl;frame.classList.remove('hidden')}restrictionBox.className='restrictionStatus warning';restrictionBox.innerHTML=`<strong>✈️ Contrôle AirOps positionné</strong><p>AirOps est maintenant centré sur <b>${lat.toFixed(5)}, ${lon.toFixed(5)}</b>.</p><p>La carte intégrée permet de consulter directement les couches AirOps : <b>NOTAM, SUP-AIP, RTBA/R368, arrêtés, espaces naturels et sites privés</b>.</p><small>⚠️ AirOps ne fournit pas ici une API publique documentée permettant à l’application GitHub Pages de lire automatiquement le contenu des popups. Le résultat des zones est donc affiché directement dans la carte AirOps intégrée, sans inventer de données.</small>`}
document.querySelector('#locateBtn').onclick=()=>{const s=document.querySelector('#locationStatus');if(!navigator.geolocation){s.textContent='Géolocalisation non disponible sur cet appareil.';return}s.textContent='Recherche de ta position…';navigator.geolocation.getCurrentPosition(p=>{const lat=p.coords.latitude,lon=p.coords.longitude;s.textContent=`Position : ${lat.toFixed(5)}, ${lon.toFixed(5)}.`;checkRestrictions(lat,lon);document.querySelector('#map').classList.remove('hidden');if(!map){map=L.map('map').setView([lat,lon],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}else map.setView([lat,lon],14);if(marker)marker.remove();marker=L.marker([lat,lon]).addTo(map).bindPopup('Ta position').openPopup()},()=>{s.textContent='Position indisponible. Autorise la localisation puis réessaie.';restrictionBox.className='restrictionStatus warning';restrictionBox.classList.remove('hidden');restrictionBox.innerHTML='⚠️ Autorise la géolocalisation pour lancer le contrôle AirOps.'},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})};
document.querySelector('#mapBtn')?.addEventListener('click',()=>window.open('https://www.geoportail.gouv.fr/donnees/restrictions-uas-categorie-ouverte-et-aeromodelisme','_blank','noopener'));